### PR TITLE
Drawer Inheritable Props

### LINKED ISSUE #28: DrawerNavGroup.onSelect should be renamed and moved to DrawerBody
#### Describe the bug
The current naming is confusing

#### What is the expected behavior?
User should be able to call like onItemSelect on DrawerBody instead of DrawerNavGroup

#### What are the steps to reproduce?
N/A

#### Screenshots or links to minimum reproduction example
N/A

#### Anything else to add?
This is originally used for dismissing UserMenu, but can be useful in other contexts, too.

>​[1:06 PM] Boyle, Joseph P
>    It could be useful in the drawer context too, like if we pass back the selected itemID or something

### LINKED ISSUE #34: NavGroup Props should be exposed at the Drawer/DrawerBody Level
#### Describe the desired behavior
Some of the props that would likely be applied across nav groups (e.g. chevron, expandIcon, activeColor, etc.) should be able to be set in one place.

#### Describe the current behavior
Currently these have to be set on each navGroup independently even . if the values are the same.

#### Is this request related to a current issue?
Identified as part of the nested drawer items work. Needed before 3.0.0

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #28, fixes #34  .

### Lift/extend 18 props

Apply `PXBlueDrawerInheritableProperties` and `PXBlueDrawerInheritableGroupProperties` to `Drawer`, `DrawerBody`, `DrawerNavGroupProps` and (Nested)`NavItem`:

| Name                      | Description                                                  | Type               | Default                                                      |
| ------------------------- | ------------------------------------------------------------ | ------------------ | ------------------------------------------------------------ |
| activeItemBackgroundColor | Background color for the 'active' item                       | `string`           | (theme.palette.type === 'light' ? primary50Color : theme.palette.primary.main) |
| activeItemBackgroundShape | shape of the active item background                          | `'round'|'square'` | round                                                        |
| activeItemFontColor       | Font color for the 'active' item                             | `string`           | (theme.palette.type === 'light' ? theme.palette.primary.main : theme.palette.primary.contrastText) |
| activeItemIconColor       | Icon color for the 'active' item                             | `string`           | (theme.palette.type === 'light' ? theme.palette.primary.main : theme.palette.primary.contrastText) |
| chevron                   | Whether to have chevrons for all menu items                  | `boolean`          |                                                              |
| collapseIcon              | Icon used to collapse drawer<br />default is expandIcon rotated 180 degrees | `JSX.Element`      | `expandIcon` rotated 180 degree                              |
| divider                   | Whether to show a line between all items                     | `boolean`          | true                                                         |
| expandIcon                | Icon used to expand drawer                                   | `JSX.Element`      | `<ExpandLess />` at top-level, `<ArrowDropUp />` otherwise   |
| hidePadding               | Whether to hide the paddings reserved for menu item icons    | `boolean`          |                                                              |
| itemFontColor             | The color used for the item text                             | `string`           | gray[500]                                                    |
| itemIconColor             | The color used for the icon                                  | `string`           | gray[500]                                                    |
| onItemSelect              | internal API<br />will apply to all menu items when onClick  | `() => void`       |                                                              |
| ripple                    | Whether to apply material ripple effect to items             | `boolean`          | true                                                         |

And there are some properties that applies to only `Drawer`, `DrawerBody`, and `DrawerNavGroupProps` (so not `NavItem`):

| Name                  | Description                                                  | Type      | Default                                                      |
| --------------------- | ------------------------------------------------------------ | --------- | ------------------------------------------------------------ |
| activeItem            | itemID for the 'active' item                                 | `string`  |                                                              |
| nestedBackgroundColor | background color for nested menu items                       | `string`  | theme.palette.type === 'light' ? white[200] : black['A200'], |
| nestedDivider         | Whether to show a line between nested menu items             | `boolean` | false                                                        |
| titleColor            | Font color for group header                                  | `string`  | theme.palette.text.primary                                   |

Everything listed in these two tables are optional. On top of these, each Drawer hierarchy still has its own props -- for example, `DrawerBody` has `backgroundColor`, and `DrawerNavGroup` has `items`.

Updated storybook story (mostly Drawer with full config) to reflect the changes. Although it is debatably complex... 

(Note that I have not changed the readme of Drawer and UserMenu yet. Making a draft PR so that we can discuss the proposed new API.)

### Rename & New Props

Several tokens get renamed. Unit tests and demos have been updated to reflect the change.

* `ChannelValue.unit` now aliases `ChannelValue.units`; `Hero.unit` now aliases `Hero.units` for consistency (all other props are singular). 
* DrawerNavGroup's `onSelect` has been renamed `onItemSelect`. 
* Anything controling a NavItem / NestedNavItem, such as `activeBackgroundColor` and `fontColor`, has been renamed to include 'item' in them, such as  `activeItemBackgroundColor` and `itemFontColor`, to avoid ambiguity. These are inheritable properties that might get confusing in different drawer hierarchy levels. 
* `nestedBackgroundColor` controls the backgroundColor of the list that holds nested nav items.
* `open` is now mandatory for `Drawer`, but is renamed `drawerOpen` and optional for others as an internal API.

### MISC

* Fixed a bug that causes items in Second DrawerNavGroup in the "Drawer with multiple DrawerNavGroups" to be unclickable
* Added some component anatomy illustrations for Channel Value and Empty State
* Changed input field background in storybook knobs to white to increase the affordance
* Arranged all the component types in alphabetical order

### CODE REVIEW

File: components/src/core/Drawer/Drawer.tsx [hunk 1]
```diff
@@ -26,18 +26,112 @@ const useStyles = makeStyles((theme: Theme) =>
...
+    // will apply to all menu items when onClick
+    onItemSelect?: () => void;
+
+    // Whether to apply material ripple effect to items
+    ripple?: boolean;
+};
+
+// type shared by Drawer, DrawerBody, DrawerNavGroup
+// inheritable props but not for NestedNavItem
+export type PXBlueDrawerInheritableGroupProperties = {
```
Comment (joebochill) [inline components/src/core/Drawer/Drawer.tsx]: `PXBlueDrawerNavGroupInheritableProperties`?

File: components/src/core/Drawer/Drawer.tsx [hunk 2]
```diff
@@ -26,18 +26,112 @@ const useStyles = makeStyles((theme: Theme) =>
...
+
+    // background color for nested menu items
+    nestedBackgroundColor?: string;
+
+    // Whether to show a line between nested menu items
+    nestedDivider?: boolean;
+
+    // internal API (public only for Drawer)
+    // Whether the group is expanded
+    open?: boolean;
```
Comment (joebochill) [inline components/src/core/Drawer/Drawer.tsx]: open is a required prop for the Drawer, but here it is listed as optional.

File: components/src/core/Drawer/Drawer.tsx [hunk 3]
```diff
@@ -26,18 +26,112 @@ const useStyles = makeStyles((theme: Theme) =>
...
+
 export type DrawerComponentProps = {
-    open: boolean;
+    // drawer width
     width?: number;
-} & Omit<DrawerProps, 'translate'>;
+
+    // types of drawer
+    // only open or variant is allowed but not both
+    variant?: 'permanent' | 'persistent' | 'temporary';
```
Comment (joebochill) [inline components/src/core/Drawer/Drawer.tsx]: 1) this could just be inherited from DrawerProps (MUI)
2) we shouldn't allow this until we've actually implemented the different behaviors for the variants

File: components/src/core/Drawer/Drawer.tsx [hunk 4]
```diff
@@ -26,18 +26,112 @@ const useStyles = makeStyles((theme: Theme) =>
...
+} & PXBlueDrawerInheritableGroupProperties &
+    Omit<DrawerProps, 'translate'>;
 
 export const DrawerComponent: React.FC<DrawerComponentProps> = (props) => {
-    let hoverDelay: any;
+    let hoverDelay: NodeJS.Timeout;
     const classes = useStyles(props);
     const theme = useTheme();
     const [hover, setHover] = useState(false);
+    const {
```
Comment (joebochill) [inline components/src/core/Drawer/Drawer.tsx]: I like the addition of 'item' in these prop names, that makes a lot more sense to me

File: components/src/core/Drawer/Drawer.tsx [hunk 5]
```diff
@@ -135,7 +248,35 @@ export const DrawerComponent: React.FC<DrawerComponentProps> = (props) => {
...
+    chevron: PropTypes.bool,
+    collapseIcon: PropTypes.element,
+    divider: PropTypes.bool,
+    expandIcon: PropTypes.element,
+    hidePadding: PropTypes.bool,
+    itemFontColor: PropTypes.string,
+    itemIconColor: PropTypes.string,
+    ripple: PropTypes.bool,
+};
+export const PXBlueDrawerInheritableGroupPropertiesPropTypes = {
```
Comment (joebochill) [inline components/src/core/Drawer/Drawer.tsx]: `PXBlueDrawerNavGroupInheritablePropertiesPropTypes`

File: components/src/core/Drawer/DrawerBody.tsx [hunk 6]
```diff
@@ -12,64 +14,67 @@ const useStyles = makeStyles({
...
-                        : {}
+                if (child.type && child.type.displayName !== 'DrawerNavGroup') return child;
+                const groupProps: DrawerNavGroupProps = child.props;
+
+                // for any DrawerNavGroup, if a prop is not set (undefined), inherit from the DrawerBody
+                // open and onItemSelect is always determined by DrawerBody
+                return (
+                    <DrawerNavGroup
+                        {...groupProps}
+                        key={index.toString()}
```
Comment (joebochill) [inline components/src/core/Drawer/DrawerBody.tsx]: index alone is not going to be a unique key across the application...do something a little more descriptive

File: components/src/core/Drawer/DrawerBody.tsx [hunk 7]
```diff
@@ -12,64 +14,67 @@ const useStyles = makeStyles({
...
+                        activeItemBackgroundColor={
+                            groupProps.activeItemBackgroundColor || bodyProps.activeItemBackgroundColor
+                        }
+                        activeItemFontColor={groupProps.activeItemFontColor || bodyProps.activeItemFontColor}
+                        activeItemIconColor={groupProps.activeItemIconColor || bodyProps.activeItemIconColor}
+                        activeItemBackgroundShape={
+                            groupProps.activeItemBackgroundShape || bodyProps.activeItemBackgroundShape
+                        }
+                        backgroundColor={bodyProps.backgroundColor}
+                        chevron={groupProps.chevron === undefined ? bodyProps.chevron : groupProps.chevron}
```
Comment (joebochill) [inline components/src/core/Drawer/DrawerBody.tsx]: Why the mix of `||` and ternary operators? Would it make sense to functionalize this somehow to make it more readable/maintainable?

File: components/src/core/Drawer/DrawerBody.tsx [hunk 8]
```diff
@@ -12,64 +14,67 @@ const useStyles = makeStyles({
...
+                        }
+                        itemFontColor={groupProps.itemFontColor || bodyProps.itemFontColor}
+                        itemIconColor={groupProps.itemIconColor || bodyProps.itemIconColor}
+                        nestedDivider={
+                            groupProps.nestedDivider === undefined ? bodyProps.nestedDivider : groupProps.nestedDivider
+                        }
+                        nestedBackgroundColor={groupProps.nestedBackgroundColor || bodyProps.nestedBackgroundColor}
+                        ripple={groupProps.ripple === undefined ? bodyProps.ripple : groupProps.ripple}
+                        onItemSelect={bodyProps.onItemSelect}
+                        open={bodyProps.open}
```
Comment (joebochill) [inline components/src/core/Drawer/DrawerBody.tsx]: should we rename the `open` prop to `drawerOpen` similar to how we handled the 'item' props? This could be confusing (open seems like it could refer to the open/close state of nested drawer items)

File: components/src/core/Drawer/DrawerNavGroup.tsx [hunk 9]
```diff
@@ -189,81 +135,75 @@ function NavigationListItem(
...
-        subtitle,
-        items: subItems,
-        divider: itemDivider,
-        itemID,
-        chevron: itemChevron,
-        collapseIcon,
-        expandIcon,
-    } = navItem;
-    // only allow icons for the top level items
-    const icon = !depth ? (navItem as NavItem).icon : undefined;
```
Comment (joebochill) [inline components/src/core/Drawer/DrawerNavGroup.tsx]: Did we lose the check here for not allowing icons on nested items?

File: demos/storybook/.storybook/manager-head.html [hunk 10]
```diff
@@ -26,4 +26,11 @@
     .css-cz6gk6 {
         color: #007bc1 !important; /* Blue[500] */
     }
+
+    .css-1lq66z2,
+    .css-106odw5,
+    .css-1j4ctyr,
+    .css-1ypp2lh {
+        background: white !important;
+    }
```
Comment (joebochill) [inline demos/storybook/.storybook/manager-head.html]: this will also need to be replicated in Angular and RN storybooks

File: demos/storybook/stories/drawer/with-full-config.tsx [hunk 11]
```diff
@@ -176,45 +289,28 @@ export const withFullConfig = (context: DrawerStoryContext): StoryFnReactReturnT
...
-            >
-                <DrawerNavGroup
-                    activeItem={context.state.selected}
-                    divider={bodyDividers}
-                    items={links1}
-                    title={groupTitle1}
-                />
+        <Drawer key={'drawer'} activeItem={context.state.selected} {...drawerKnobs}>
+            <DrawerHeader {...headerKnobs} />
+            <DrawerBody {...bodyKnobs}>
```
Comment (joebochill) [inline demos/storybook/stories/drawer/with-full-config.tsx]: I'm conflicted on this change. I like the idea of having all of the knobs defined together in an object, but now the code snippets in the Story tab are not very useful.

File: demos/storybook/stories/drawer/with-multiple-DrawerNavGroups.tsx [hunk 12]
```diff
@@ -7,16 +7,22 @@ import React from 'react';
...
 import { navGroupItems1 } from './with-basic-config';
 
-export const navGroupItems2: NavItem[] = [
+export const navGroupItems2 = (context: DrawerStoryContext): NavItem[] => [
     {
         title: 'Overview',
         itemID: 'group2-1',
         icon: <Dashboard />,
+        onClick: (): void => {
+            context.store.set({ selected: 'group2-1' });
```
Comment (joebochill) [inline demos/storybook/stories/drawer/with-multiple-DrawerNavGroups.tsx]: Is setting the selected item going to break the context in stories that don't have a second navgroup?

File: demos/storybook/stories/drawer/with-nested-list-items.tsx [hunk 13]
```diff
@@ -25,26 +25,53 @@ const componentLibrary = 'Component Library';
...
+        case '<PinDrop />':
+            return <PinDrop />;
+        case '<Remove />':
+            return <Remove />;
+        case '<AddAPhoto />':
+            return <AddAPhoto />;
+        case 'undefined':
+        default:
+            return undefined;
+    }
```
Comment (joebochill) [inline demos/storybook/stories/drawer/with-nested-list-items.tsx]: This function is defined in several places, should we make it a utility?

File: components/src/core/Drawer/DrawerBody.tsx (hunk 7 above)
Comment (huayunh) [reply components/src/core/Drawer/DrawerBody.tsx]: the `a?b:c` is used only on boolean values and is necessary. Or are you thinking about turning this into a function?

File: components/src/core/Drawer/DrawerNavGroup.tsx (hunk 9 above)
Comment (huayunh) [reply components/src/core/Drawer/DrawerNavGroup.tsx]: Good catch -- looks like it might be some merge conflict misfortune thing

File: demos/storybook/stories/drawer/with-full-config.tsx (hunk 11 above)
Comment (huayunh) [reply demos/storybook/stories/drawer/with-full-config.tsx]: They are still useful, just stacked together rather than listed out individually.

File: demos/storybook/stories/drawer/with-multiple-DrawerNavGroups.tsx (hunk 12 above)
Comment (huayunh) [reply demos/storybook/stories/drawer/with-multiple-DrawerNavGroups.tsx]: No. It will just have everything unselected.

File: demos/storybook/stories/drawer/with-nested-list-items.tsx (hunk 13 above)
Comment (huayunh) [reply demos/storybook/stories/drawer/with-nested-list-items.tsx]: I tried, and then storybook tried to recognize every .tsx file as a story. I did not look deeper into that.

File: components/src/core/Drawer/Drawer.tsx (hunk 3 above)
Comment (huayunh) [reply components/src/core/Drawer/Drawer.tsx]: Let me do that in a separate PR

File: demos/storybook/.storybook/manager-head.html (hunk 10 above)
Comment (huayunh) [reply demos/storybook/.storybook/manager-head.html]: I have some local troubles with RN storybook so I will go ahead and do that for Angular

Comment (huayunh) [reply demos/storybook/.storybook/manager-head.html]: https://github.com/pxblue/angular-component-library/pull/20

File: demos/storybook/stories/drawer/with-full-config.tsx (hunk 11 above)
Comment (joebochill) [reply demos/storybook/stories/drawer/with-full-config.tsx]: But if a user wants to copy-paste the snippet, they have no idea what any of the props actually are unless they go digging around in the source:
image

Comment (joebochill) [reply demos/storybook/stories/drawer/with-full-config.tsx]: @emclaug2 what do you think about this?

File: demos/storybook/stories/welcome.stories.tsx [hunk 14]
```diff
@@ -11,16 +11,16 @@ export const stories = storiesOf('Intro/Overview', module);
...
+            color: appliedTheme.palette.primary.contrastText,
+            backgroundColor: appliedTheme.palette.primary.main,
             backgroundImage: `url(${backgroundImage})`,
             height: '100%',
             width: '100%',
             display: 'flex',
             alignContent: 'center',
             justifyContent: 'center',
+            backgroundSize: '110%',
+            backgroundPosition: 'center',
```
Comment (joebochill) [inline demos/storybook/stories/welcome.stories.tsx]: I would leave the background alone here so we stay consistent across all of the storybooks

File: docs/Drawer.md [hunk 15]
```diff
@@ -39,6 +39,8 @@ import { Drawer, DrawerHeader, DrawerSubheader, DrawerBody, DrawerNavGroup, Draw
 
 </div>
 
+You may use the inheritables to override the default styles -- see the [Inheritables](#interitables) section below.
```
Comment (joebochill) [inline docs/Drawer.md]: could we maybe do this in the API table, e.g.:
```
| Prop Name | Description |
|------------|------------|
| width          | blah blah    |
| [...sharedProps](#sharedprops) | Props that can be set at any level in the drawer hierarchy |
```

File: docs/Drawer.md [hunk 16]
```diff
@@ -216,6 +196,34 @@ import DrawerFooter from '@pxblue/react-components/core/Drawer';
 </DrawerFooter>
 ```
 
+## Interitables
+There are a few optional props that controls the cosmetics of the drawer items and are shared between `Drawer`, `DrawerNavGroup`, `NavItem` and `NestedNavItem`. These properties are inheritable, meaning that the children can inherit the props from their parents if the child prop is set to undefined, and can override the parent props by setting child props to certain values.
```
Comment (joebochill) [inline docs/Drawer.md]:
```suggestion
## Shared Props
The following props can be set at any level in the drawer hierarchy (`Drawer`, `DrawerNavGroup`, `NavItem`, or `NestedNavItem`). If they are set on a parent, they will be used for all children. For more customization, you can set these props on individual children and they will override any value set on the parent.
```

File: docs/Drawer.md [hunk 17]
```diff
@@ -216,6 +196,34 @@ import DrawerFooter from '@pxblue/react-components/core/Drawer';
 </DrawerFooter>
 ```
 
+## Interitables
+There are a few optional props that controls the cosmetics of the drawer items and are shared between `Drawer`, `DrawerNavGroup`, `NavItem` and `NestedNavItem`. These properties are inheritable, meaning that the children can inherit the props from their parents if the child prop is set to undefined, and can override the parent props by setting child props to certain values. 
+
+| Name                      | Description                                                | Type               | Required | Default                                                      |
+| ------------------------- | ---------------------------------------------------------- | ------------------ | -------- | ------------------------------------------------------------ |
+| activeItemBackgroundColor | Background color for the 'active' item                     | `string`           | no       | (theme.palette.type === 'light' ? primary50Color : theme.palette.primary.main) |
```
Comment (joebochill) [inline docs/Drawer.md]: primary50color is a variable isn't it? It would be more helpful to show the actual value I think. Or maybe for these types of props, we can just say `varies for light/dark theme`

File: demos/storybook/stories/drawer/with-full-config.tsx [hunk 18]
```diff
@@ -34,69 +49,157 @@ const devices = 'Devices';
...
-        350,
-        {
-            range: true,
-            min: 200,
-            max: 700,
-            step: 50,
-        },
-        drawerGroupId
-    );
+    const drawerKnobs: DrawerComponentProps = {
```
Comment (joebochill) [inline demos/storybook/stories/drawer/with-full-config.tsx]: We need to reduce some of these knobs...we don't need to show every knob at every level. Right now, the 'activebackgroundshape' knob on the drawer does nothing, because there's a knob for it on the navgroups that overrides it. I would suggest showing the shared prop knobs on the drawer, and the other levels only showing the props specific to them.

Comment (huayunh) [reply demos/storybook/stories/drawer/with-full-config.tsx]: Yes I agree... I was trying to think of a better way to show how the props can inherit each other. I tried to have two navGroups, but that is equally confusing.

File: demos/storybook/stories/welcome.stories.tsx (hunk 14 above)
Comment (huayunh) [reply demos/storybook/stories/welcome.stories.tsx]: Angular & React Native used size 200% and center. Changing...

File: components/src/core/Drawer/DrawerBody.tsx [hunk 19]
```diff
@@ -12,64 +17,69 @@ const useStyles = makeStyles({
...
+                    />
                 );
             })}
         </div>
     );
 };
 
 DrawerBody.displayName = 'DrawerBody';
+
+// @ts-ignore
```
[the remark this answers is not in the document]
Comment (huayunh) [reply components/src/core/Drawer/DrawerBody.tsx]: It keeps complaining that the activeItemBackgroundShape propType (defined in Drawer.tsx) has type string and is not assignable with the type `'round' | 'square'`. But if I copy paste the same content, the warning disappears.

[the remark this answers is not in the document]
Comment (joebochill) [reply components/src/core/Drawer/DrawerBody.tsx]: Hmm, strange...I see it though

File: demos/storybook/stories/hero/with-full-config.tsx [hunk 20]
```diff
@@ -11,7 +11,7 @@ import { WITH_FULL_CONFIG_STORY_NAME } from '../../src/constants';
 export const withFullConfig = (): StoryFnReactReturnType => (
     <Hero
         label={text('label', 'Velocity')}
-        units={text('units', 'RPM')}
+        units={text('unit', 'RPM')}
```
Comment (joebochill) [inline demos/storybook/stories/hero/with-full-config.tsx]:
```suggestion
        units={text('units', 'RPM')}
```

File: demos/storybook/stories/welcome.stories.tsx [hunk 21]
```diff
@@ -11,16 +11,16 @@ export const stories = storiesOf('Intro/Overview', module);
...
+            color: appliedTheme.palette.primary.contrastText,
+            backgroundColor: appliedTheme.palette.primary.main,
             backgroundImage: `url(${backgroundImage})`,
             height: '100%',
             width: '100%',
             display: 'flex',
             alignContent: 'center',
             justifyContent: 'center',
+            backgroundSize: '200%',
+            backgroundPosition: 'center',
```
Comment (joebochill) [inline demos/storybook/stories/welcome.stories.tsx]: If we are changing the background, we need to change all of the storybooks to use the same style

File: components/src/core/Drawer/DrawerHeader.tsx [hunk 22]
```diff
@@ -28,6 +28,7 @@ const useStyles = makeStyles((theme: Theme) =>
             flexDirection: 'column',
             width: 'calc(100% - 56px)',
             boxSizing: 'border-box',
+            zIndex: 1,
```
Comment (joebochill) [inline components/src/core/Drawer/DrawerHeader.tsx]: need to add this on navigation class too or the icon disappears
