### PR TITLE
Accessibility update (2)

### LINKED ISSUE #117: ItemID marked as required in UserMenu menuGroups
#### Describe the bug
When using the UserMenu component, typescript complains that the property itemID (from DrawerNavItem) is required.

#### What is the expected behavior?
This property is not required in the UserMenu component.

#### Screenshots or links to minimum reproduction example
image

### PR DESCRIPTION
**Pull request by huayunh**
Fixes #117.

Changes proposed in this Pull Request:
- Address a few more a-11-y issues 
- itemID no longer required in user menu

### CODE REVIEW

File: components/src/core/UserMenu/UserMenu.tsx [hunk 1]
```diff
@@ -165,7 +166,10 @@ export const UserMenu: React.FC<UserMenuProps> = (props) => {
                         itemIconColor={group.iconColor}
                         itemFontColor={group.fontColor}
                         title={group.title}
-                        items={group.items}
+                        items={group.items.map(
+                            (item: UserMenuItem, itemIndex: number): NavItem =>
+                                Object.assign({ itemID: itemIndex.toString() }, item)
+                        )}
```
Comment (joebochill) [inline components/src/core/UserMenu/UserMenu.tsx:172]: this is a little hacky, but we can let it slide
