### PR TITLE
Changed import statements of material-ui components to default imports

### LINKED ISSUE #321: Switch to more size-efficient import syntax
#### Describe the bug
When using our library in a project, all of the Material-UI components are included in the bundle even if they are never used.

#### What is the expected behavior?
Only the components that are being used should be part of the final bundle

#### What are the steps to reproduce?
1. Create a new blank project with the CLI
2. Run the build command
3. Use a bundle analyzer to see that _all_ of the Material-UI components code is included in the final bundle, even the more obscure ones.

#### Screenshots or links to minimum reproduction example
image
		
#### Anything else to add?
This is reported by the Green team. We were doing this correctly before, but it seems like we forgot about this for some of the more recent additions that we have made.

We need to update our component import syntax to use default exports instead of named exports from the index/barrel (i.e., we should not import anything from '@material-ui/core' in our library:

https://material-ui.com/guides/minimizing-bundle-size/#option-1

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #321

#### Changes proposed in this Pull Request:
- Changed import statements of material-ui components to default imports
- Comp props and other things than components still be imported as named imports

#### To Test:
1. Start a new React project with the pxblue cli via command line prompt npx -p @pxblue/cli pxb new (https://pxblue.github.io/development/cli) 
2. Run yarn build from the root of the react-component-library in the updated branch you have locally.
3. The previous command should create a dist folder... copy the contents of that dist folder into your new cli generated projects node_modules/@pxblue/react-native-components folder.
4. Add the source-map-explorer to the cli generated project as a dev dependency and add "analyze" script "analyze": "source-map-explorer 'build/static/js/*.js'" 
5. Run yarn build in the new cli project
6. Run yarn analyze
7. Compare the new chart to the one posted in the PR

### CODE REVIEW

File: components/src/core/AppBar/AppBar.tsx [hunk 1]
```diff
@@ -1,13 +1,6 @@
...
-import {
-    AppBar as MuiAppBar,
-    AppBarProps as MuiAppBarProps,
-    createStyles,
-    makeStyles,
-    Theme,
-    useMediaQuery,
-    useTheme,
-} from '@material-ui/core';
+import { createStyles, makeStyles, Theme, useMediaQuery, useTheme } from '@material-ui/core';
```
Comment (huayunh) [inline components/src/core/AppBar/AppBar.tsx:2]: You may want to look into the source code's `d.ts` in node_modules  to see from where these are exported.

```suggestion
import createStyles from '@material-ui/styles/createStyles';
import makeStyles from '@material-ui/styles/makeStyles';
import { Theme } from '@material-ui/core/styles/createMuiTheme';
import useTheme from '@material-ui/core/styles/useTheme';
import useMediaQuery from '@material-ui/core/useMediaQuery';
```

Comment (bkarambe) [reply components/src/core/AppBar/AppBar.tsx:2]: Sure. Thanks for the feedback

Comment (bkarambe) [reply components/src/core/AppBar/AppBar.tsx]: @huayunh Updated the PR with the suggested changes.

**Comment by joebochill** [comment]
When testing this one, you guys will want to actually build a sample project (like the showcase) and analyze the bundle to make sure the unused components aren't included. We have this set up in doc-it (see the analyze command in package.json) to reference how to see the bundle size breakdown.

**Comment by huayunh** [comment]
Hmm. I did the bundle analyzer thing in the showcase, and the current branch has no diff from what's in `dev`.

image

Suraj, would you set up a bundle analyzer in `demos/showcase/package.json`, using the method Joe described above? `demos/showcase` is a submodule pointing to https://github.com/pxblue/react-showcase-demo, so you may want to make a pull request there too.

**Comment by huayunh** [comment]
image
I just noticed that the tests are running in Electron by default

**Comment by bkarambe** [comment]
> Hmm. I did the bundle analyzer thing in the showcase, and the current branch has no diff from what's in `dev`.
> 
> image
> 
> Suraj, would you set up a bundle analyzer in `demos/showcase/package.json`, using the method Joe described above? `demos/showcase` is a submodule pointing to https://github.com/pxblue/react-showcase-demo, so you may want to make a pull request there too.

Sure @huayunh will do that.

**Comment by joebochill** [comment]
The showcase might be a tricky one to do the bundle analysis on since we _are_ using a lot of the components (in order to demo them). It might be good to also test a bare-bones new project out of the CLI (with a alpha/beta version of this updated component library)

**Comment by bkarambe** [comment]
> The showcase might be a tricky one to do the bundle analysis on since we _are_ using a lot of the components (in order to demo them). It might be good to also test a bare-bones new project out of the CLI (with a alpha/beta version of this updated component library)

Sure Joe, following it.

**Comment by bkarambe** [comment]
@joebochill I created a blank demo project using cli and run analyzer.
ss_original

**Comment by joebochill** [comment]
The one from the blank project looks good (54kb vs. 270kb in the showcase). @bkarambe was that a blank CLI project from the CLI without any modification, or a blank project from the CLI and you installed a version of the component library with your changes in it?

**Comment by joebochill** [comment]
I pulled down your branch and it looks like you got them all 👍

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
Might want to add an entry for the changelog as well (We can cal it 5.3.2 for now until we see what else might go in to that version).

**Comment by bkarambe** [comment]
> The one from the blank project looks good (54kb vs. 270kb in the showcase). @bkarambe was that a blank CLI project from the CLI without any modification, or a blank project from the CLI and you installed a version of the component library with your changes in it?

@joebochill It was a blank cli project, where I just replaced a pxblue modules in modules with the react-component-library modules.

File: CHANGELOG.md [hunk 2]
```diff
@@ -244,3 +244,7 @@ Fixes a bug in icon size for inline `<ChannelValue>` components.
 ## v0.0.1 (May 24, 2019)
 
 Initial beta release
+
+### Updated 
+
+Updated react component library to 5.3.2
```
Comment (huayunh) [inline CHANGELOG.md:250]: You only add change logs at the top. And you add descriptions to what's been updated. You can have a look at how other packages are doing this (like this changelog in [Angular component library](https://github.com/pxblue/angular-component-library/blob/dev/CHANGELOG.md))

Comment (huayunh) [inline CHANGELOG.md:250]: You only add the changelog at the top. And it should be more descriptive. See how Angular component library is doing it:

https://github.com/pxblue/angular-component-library/blob/dev/CHANGELOG.md

Comment (bkarambe) [reply CHANGELOG.md]: @huayunh Thanks for the feedback. Updated the PR.

File: CHANGELOG.md [hunk 3]
```diff
@@ -244,3 +244,17 @@ Fixes a bug in icon size for inline `<ChannelValue>` components.
...
+
+-   Updated the import statements of material-ui components and icons to be default imports instead of named imports, so that the only components that are being used should be part of final bundle
+
+    ```typescript
+    /* Old import syntax */
+    import { ComponentName } from '@material-ui/core';
+
+    /* New import syntax */
+    import ComponentName from '@material-ui/core/ComponentName';
+    ```
```
Comment (joebochill) [inline CHANGELOG.md:260]: We can keep this entry pretty simple:
```suggestion
## v5.3.2 (unpublished)

### Updated

-   Import material-ui components via default imports instead of named imports to reduce overall bundle size.
```

And this should be at the top of the file instead of the bottom (most recent version appears first). You'll get the hang of the changelog updates once you do a few. We've been trying to follow the changelog format defined by Keep A Changelog: https://keepachangelog.com/en/1.0.0/

Comment (bkarambe) [reply CHANGELOG.md]: @joebochill Updated the PR.

**Review by emclaug2 — APPROVED** [review]

**Review by joebochill — APPROVED** [review]
