### PR TITLE
Fix menu group icon color bug

### LINKED ISSUE #305: UserMenu menuGroups iconColor prop doesn't change the icon color
#### Describe the bug
The UserMenu menuGroups iconColor prop doesn't change the menu item icon color.

#### What is the expected behavior?
The UserMenu menuGroups iconColor prop should change the menu item iconColor.

#### What are the steps to reproduce?
1. Go to storybook and navigate to the UserMenu with custom colors story
2. Update the menu menugroups.iconColor prop via knobs
3. Observe icon color not changing

#### Screenshots or links to minimum reproduction example
Screen Shot 2021-07-22 at 7 25 56 AM
		
#### Anything else to add?
It looks like the component is accepting the menugroups.iconColor prop properly, then manually overwriting the color and setting it to `theme.palette.text.secondary`.

### PR DESCRIPTION
**Pull request by doctorbebo**
Fixes #305 

#### Changes proposed in this Pull Request:
- Fix menu group icon color bug

### CODE REVIEW

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
Make sure to include this in a changelog entry when you fix the next bug.

File: components/src/core/UserMenu/UserMenu.tsx [hunk 1]
```diff
@@ -189,7 +189,7 @@ const UserMenuRender: React.ForwardRefRenderFunction<unknown, UserMenuProps> = (
                             (item: UserMenuItem, itemIndex: number): NavItem =>
                                 Object.assign({ itemID: itemIndex.toString() }, item, {
                                     InfoListItemProps: Object.assign(
-                                        { iconColor: theme.palette.text.secondary },
+                                        { iconColor: group.iconColor || theme.palette.text.secondary },
```
Comment (joebochill) [inline components/src/core/UserMenu/UserMenu.tsx:192]: As it turns out, the individual menu items also take a color prop for the icon that they inherit from the DrawerNavItem component: `itemIconColor`. So we will actually want to account for that as well:
```suggestion
                                        { iconColor: UserMenuItem.itemIconColor || group.iconColor || theme.palette.text.secondary },
```

**Review by joebochill — CHANGES_REQUESTED** [review]
I suppose we can get that changelog entry included in this PR now if you're going to also make the suggested update.

**Review by joebochill — APPROVED** [review]
